### ISSUE TITLE
Time step

### ISSUE THREAD

**Issue by Sushmitha46** [matteobernardini/STREAmS#10]
Hello,
I am trying to understand at what actual time steps are field files getting generated. The time variable mentioned in output files are at intervals of 5 as specified by us using "dtsave", but what does the digit signify. And is the time step constant or does it vary?
Thank you

**Comment by davidem88** [comment]
I didn't understand the first question, what do you mean by "digit"? As for the time step, it is not constant. The time step is recomputed to keep a constant CFL number, specified in input.

**Comment by Sushmitha46** [comment]
In dtsave = 5, you had told that it is a non dimensional time, by what time scale is it non-dimensionalised?
If it is non dimensionalised using incoming boundary layer thickness and free stream velocity, then how do i interpret the value of boundary layer thickness and free stream velocity

**Comment by davidem88** [comment]
The reference velocity is the speed of sound at the reference temperature (free-stream) and the boundary layer thickness at the inflow. Please refer to the documentation https://streams-cfd.github.io/STREAmS-2/manual/flow_cases.html#nondimensional-governing-equations
