### ISSUE TITLE
Streams2

### ISSUE THREAD

**Issue by Sushmitha46** [matteobernardini/STREAmS#13]
Hello,
I have run few cases using STREAmS 1, is it possible to **continue** those runs using STREAmS 2.

**Comment by davidem88** [comment]
Yes, it is. However, only if you restart with restart_type = 1. You'll need rst.bin from STREAmS 1, and you'll have to write the file field_info.dat manually. Additionally, you have to remove the ghost nodes in the mesh files (x.dat,y.dat,z.dat).
