### ISSUE TITLE
field files

### ISSUE THREAD

**Issue by Sushmitha46** [matteobernardini/STREAmS#14]
Hello,
I am trying to understand the unsteady mechanism in the Interaction Zone, in order to do this I will need the field files to be written at a constant time interval, is it possible for me to print field files at a constant time interval?
Thank you

**Comment by davidem88** [comment]
You can resample the data. Alternatively, you can set cfl to a negative value in the input file. In this case 'cfl' has the meaning of dt and it is kept constant during the simulation
