### ISSUE TITLE
cf files

### ISSUE THREAD

**Issue by Sushmitha46** [matteobernardini/STREAmS#16]
Hello,
Can you please provide insight on what each column in cfz_nnn_nnnn and wavplot_nnn_nnnn.dat files represent. These files are generated but there is not much information on what data it is trying to write.

**Comment by davidem88** [comment]
This is explained in the documentation

**Comment by Sushmitharao46** [comment]
streams2 documentation has no information regarding these files and the documentation of streams1 has information regarding cf files but has no info on cfz, cfstart and wavplot files.
Can you please provide information on what each column represents.
Thank you.

**Comment by davidem88** [comment]
cfz files are printed for each block and at given time steps. They contain the following variables x(i),cf,retau,shapef,shapefinc
