### ISSUE TITLE
clarification on database_bl.dat for SBLI example

### ISSUE THREAD

**Issue by Sushmitha46** [matteobernardini/STREAmS#2]
If I want to simulate a complete new case on Shock impingement on flat plate with input conditions which are different from example test case given in the repository, do I need to change the **database_bl.dat** file. If yes, then what are the changes that I am supposed to do in the file **database_bl.dat**.

Thank you

**Comment by davidem88** [comment]
No, you don't need to change database_bl.dat, as far as your inflow friction Reynolds number is approximately between 200 and 1100.

**Comment by Sushmitha46** [comment]
Thank you for the clarification.
Further I wanted to know how to interpret the data in the file database_bl.dat, may I please get any kind of reference to understand the contents of the file.

Thank you

**Comment by davidem88** [comment]
You can see the file format in target_reystress.F90. You have the number of points and friction Reynolds number of the data, followed by the wall-normal coordinate y and Reynolds stresses profiles, u2, v2, w2 and uv.

**Comment by Sushmitha46** [comment]
Thank you for the clarification.
I tried to run the last example case "supersonic_sbli" but no output files were generated. I think, one of the reasons for this maybe because in
"https://www.researchgate.net/publication/233991167_Direct_numerical_simulation_of_transonic_shockboundary_layer_interaction_under_conditions_of_incipient_separation" the computational domain size was multiplied with boundary layer thickness and in input.dat the length values were given directly.
So, should we change those values in input.dat or are the values given in input.dat already multiplied with boundary layer thickness??
![sbli](https://user-images.githubusercontent.com/109201960/180728178-f6a06a67-2f9c-48b6-8267-7947efb63c41.png)

**Comment by davidem88** [comment]
The solver is nondimensional and the reference length scale is the boundary layer thickness at the inflow. Therefore, to reproduce the case in the paper the correct streamwise domain length is 64. What do you mean that no output files were generated? Does the code print any error? Are you running on GPU?
