### ISSUE TITLE
Time series data

### ISSUE THREAD

**Issue by Sushmitha46** [matteobernardini/STREAmS#24]
Hello,
I am trying to do low frequency unsteadiness study for sbli case and I wanted to know how to obtain time series data.
Is it possible for us to change few parameters in input.dat and get time-series data or should we ourselves make changes in code to get that data?

Thank You

**Comment by alshahriar** [comment]
It seems the code is already getting some time average statistics at specified stations in the streamwise direction. If this is what you need:  

> stat_control  xstat_num. Cumulative flow statistics are evaluate every stat_control iterations. xstat_num is the number of streamwise stations at which flow statistics are extracted and is only meaningful for boundary layer and SBLI cases (flow_type > 0).

**Comment by Sushmitha46** [comment]
In stat files the values are only updated after every 5 non dimensional time units, It does not store the statistics at every time interval. But for unsteadiness analysis I will need properties with time.
But output_streams.dat has elapsed time along with momentum residual information, is it possible to add extra columns of properties such as pressure, temperature at particular locations in output_streams.dat.
I have attached the output_strteams.dat file, the second column shows elapsed time and I want properties to be written in such small time intervals
![output_streams](https://user-images.githubusercontent.com/109201960/217456748-b794df4f-2819-4c1a-85fd-fd2cb67e99e9.PNG)

**Comment by davidem88** [comment]
See this answer for probes https://github.com/matteobernardini/STREAmS/issues/25
