### ISSUE TITLE
Time series data

### ISSUE THREAD

**Issue by dineshkumarreddyg36** [matteobernardini/STREAmS#25]
Is there a possibility of adding probes, to get time series data at a particular location for low frequency unsteadiness study?

Thank you

**Comment by davidem88** [comment]
This capability is available in STREAmS-2 https://github.com/STREAmS-CFD/STREAmS-2. You have to create an ASCII file called "probe_list.dat" in the case folder. The first line should contain the number of probes, and the following lines the list of probes coordinates x,y,x. See also singleideal.F90, line 618.

**Comment by Sushmitharao46** [comment]
If followed this, will I get the properties written after every iteration.
In the form - iteration, elapsed time and properties at those locations.
