### ISSUE TITLE
wavplot has 22 columns, can you provide information on what each column represents.

### ISSUE THREAD

**Issue by Sushmitharao46** [matteobernardini/STREAmS#26]
wavplot has 22 columns, can you provide information on what each column represents.

_Originally posted by @Sushmitharao46 in https://github.com/matteobernardini/STREAmS/issues/19#issuecomment-1437940569_

**Comment by davidem88** [comment]
It contains the coordinates x,y and the 20 mean variables in the same order as in the routine "compute_av"
