### ISSUE TITLE
probe data

### ISSUE THREAD

**Issue by dineshkumarreddyg36** [matteobernardini/STREAmS#29]
Hello,
I wanted time series data at certain points, so I added few lines at 2 places. I have attached screenshots of the same. Can you please confirm if it is correct, because those edits which I considered to be correct are not fetching me required results.
1. These few lines I have added in Solver.F90, I was tryin to open 7 new files at 7 different locations.
![solver](https://user-images.githubusercontent.com/106377425/231162591-9cb3bbb6-8936-41fb-9075-cebf16ccde63.PNG)
2. I added the below lines in printres.F90 to get the data with 7 columns (iteration number, time step, rho, rho-u, rho-v, rho-w, rho-e)
   at 7 different locations among which first 4 locations are at wall
![printres](https://user-images.githubusercontent.com/106377425/231164196-840384e0-96b7-4f2f-820a-fbbf9ee286ed.PNG)

Thank You

**Comment by davidem88** [comment]
This is not correct because only masterproc is printing and it does not have access to the entire field w. This implementation will only work when you run using 1 MPI process. I suggest switching to streams-2 where probes are already implemented.
