### ISSUE TITLE
Segmentation fault while running plot3d files

### ISSUE THREAD

**Issue by Sushmitha46** [matteobernardini/STREAmS#3]
Hello,
I tried to run supersonic channel again in CPU and compiled using intel(2020)  compiler.
![compile](https://user-images.githubusercontent.com/109201960/184888646-2cf5084d-4925-481e-b208-6424b83267fd.png)

Compilation was successfully done with no errors or warnings but still when I tried to run the code with enable_plot3d and  enable_vtk as 1, it showed segmentation error. When I disabled enable_plot3d and enable_vtk and tried to run it again, it showed segmentation error while writing .bin files.
![segmentation](https://user-images.githubusercontent.com/109201960/184892518-16e1286d-64f3-4673-a989-d452866250f1.png)
So, I wanted to know if there are any changes that are supposed to be done in code when writing plot3d and vtk files

**Comment by davidem88** [comment]
can you share the input file you used?

**Comment by Sushmitha46** [comment]
!=============================================================
!
! ███████╗████████╗██████╗ ███████╗ █████╗ ███╗   ███╗███████╗
! ██╔════╝╚══██╔══╝██╔══██╗██╔════╝██╔══██╗████╗ ████║██╔════╝
! ███████╗   ██║   ██████╔╝█████╗  ███████║██╔████╔██║███████╗
! ╚════██║   ██║   ██╔══██╗██╔══╝  ██╔══██║██║╚██╔╝██║╚════██║
! ███████║   ██║   ██║  ██║███████╗██║  ██║██║ ╚═╝ ██║███████║
! ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝
!
! Supersonic TuRbulEnt Accelerated navier stokes Solver
!
! input file
!
!=============================================================

 flow_type (0==>channel, 1==>BL, 2==>SBLI)
   0   

  Lx             Ly         Lz
 18.8571429  2.  6.283185307179586
 
 Nx     Ny     Nz
  1020    256    510
 
 Ny_wr     Ly_wr      dy+_w  jbgrid
  150       2.5         1.        0

 ng  visc_ord  ep_ord  weno_par (1==>ord_1,2==>ord_3, 3==>ord_5, 4==>ord_7)
  3     6      6      3 
 
 MPI_x_split     MPI_z_split
   1          1

 sensor_threshold   xshock_imp   deflec_shock    pgrad (0==>constant bulk)
  1.2      50.     8.        0.
      
 restart   num_iter   cfl   dt_control  print_control  io_type
   0     90000    .8       10       10      2
      
 Mach      Reynolds (friction)  temp_ratio   visc_type   Tref (dimensional)   turb_inflow
  1.5         220.           0.        1          300.                 0.75
  
 stat_control  xstat_num
  250      0

 xstat_list
   10. 20. 25.
 
 dtsave dtsave_restart  enable_plot3d   enable_vtk
  50.       50.                1              1

  rand_type
   -1

**Comment by davidem88** [comment]
This case could be too big to run with one process. Try to increase the number of processes or reduce the mesh size.

**Comment by francescosalvadore** [comment]
@Sushmitha46 I have checked and actually the plot3d writing does not work with the Intel compiler. The reason is the static declaration of grid3d. I pushed a change using allocatable memory which seems to me to fix the problem. Let us know if it's working for you now.

**Comment by Sushmitha46** [comment]
@francescosalvadore I tried to compile and run the new file, this time plot3dgrid was written but then same error followed, and I was not able to open the written plot3d files.
![plot3derror](https://user-images.githubusercontent.com/109201960/185048773-e078a260-221a-4454-9e3d-53b78a2177b6.png)

The below error was shown when I tried to open the generated plot3d file
![paraview_ploterror](https://user-images.githubusercontent.com/109201960/185048474-390e795b-6f65-4f9d-9608-62520ce47209.png)

**Comment by Sushmitha46** [comment]
@davidem88 I had previously tried to run it using 120 cores, it showed the same error.

**Comment by francescosalvadore** [comment]
@Sushmitha46, how is stacksize configured? Can you try to increase it (ulimit -s unlimited)?

**Comment by Sushmitha46** [comment]
I increased it and it worked. Thank you :)
