### ISSUE TITLE
Field files and Shock Impingement location (Shock wave Boundary layer Interaction case)

### ISSUE THREAD

**Issue by Sushmitha46** [matteobernardini/STREAmS#4]
Hello,
1. I wanted to know at what intervals are field files getting generated, if I want them to be written for every 10,000 iterations is it possible to do so? or is there any other logic behind how these files are being written?
2. If I wanted to run the SBLI case for different Mach Numbers or for different shock deflection Angles will I have to change the variable "xshock_imp"?

Thank you.

**Comment by davidem88** [comment]
1) 3D fields are written at constant time intervals. The variable "dtsave" in input.dat is the time interval at which 3D solutions are written
2) The variable "Mach" in input.dat is the free-stream Mach number. xshock_imp is the nominal impingement location of the inviscid shock, and "deflec_shock" is the shock angle. These three parameters are independent. Of course you have to make sure that they fall into the computational domain and that  xshock_imp is after the recycling station.

**Comment by Sushmitha46** [comment]
Thank you for the clarification.
