### ISSUE TITLE
stat.bin file not found

### ISSUE THREAD

**Issue by Sushmitha46** [matteobernardini/STREAmS#5]
Hello,
I tried to run the code, and it successfully ran for 158910 iterations, but when I again resubmitted the job it threw an error as shown in this file.
[sbli_supersonic.log](https://github.com/matteobernardini/STREAmS/files/9596689/sbli_supersonic.log)
But it had stat.bak file and no stat.bin file was generated in the last run, so is it possible to make the code read stat.bak instead of stat.bin and continue the iterations.

**Comment by davidem88** [comment]
You can manually rename the file before restarting:
mv stat.bak stat.bin
