### ISSUE TITLE
Mean Wall Pressure plot

### ISSUE THREAD

**Issue by Sushmitharao46** [matteobernardini/STREAmS#6]
Hello,
For the case of Shock wave - Boundary layer interaction,
1. I wanted to know if there is any file that is generated with pressure information or should we calculate it using the convective variable vector that is obtained to obtain the mean wall pressure plot.
2. Is P1 same as Pinf here?
3. How to obtain the proper value of Interaction length(L)

**Comment by Sushmitharao46** [comment]
Is the P2 required for mean wall pressure plot the pressure after impinging shock wave or the pressure after the interaction?

**Comment by matteobernardini** [comment]
1. you have to instrument the code to store the pressure
2.  no p1 is the pressure after the incident shock
3.  you can use the mean pressure field and extrapolate the reflected shock up to the wall. Then compute the distance between the impingement point and the extrapolated point
