### ISSUE TITLE
Deflection Angle

### ISSUE THREAD

**Issue by Sushmitharao46** [matteobernardini/STREAmS#7]
Hello,
There are few doubts I had related to the variable deflec_shock in input file.

According to the explanation in "preparing input.dat file", deflec_shock is the shock angle (beeta) whose default value given was 8deg in the input.dat file, but according to the paper https://doi.org/10.1016/j.cpc.2021.107906 the 8deg given is mentioned as Incidence angle of shock generator (theeta). So, I wanted to know what exactly the term deflec_shock is specifying, is it the shock angle (beeta) or deflection angle(theeta).

And if its the deflection angle what is the maximum deflection angle that we can feed into the input file.

**Comment by matteobernardini** [comment]
deflec_shock is the deflection angle (the flow deviation after the shock)
