### ISSUE TITLE
dtsave variable

### ISSUE THREAD

**Issue by Sushmitharao46** [matteobernardini/STREAmS#8]
Does the variable dtsave = 5 in input.dat file signify that field files are written after every 5 seconds?
What information is being obtained in plotxy_000.dat file?

**Comment by davidem88** [comment]
The variables in plotxy_000.dat can be checked in writerst.F90. dtsave=5 means that files are written every 5 nondimensional time units (time variable printed on screen). Please check the new code documentation available here https://streams-cfd.github.io/STREAmS-2/ for the nondimensional form of the equations. Also consider signing up for the newsletter https://streamsdns.substack.com/.
